# Cargar variables de .env
spring.config.import=optional:file:.env[.properties]

# DataSource
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File upload limits
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# MinIO
minio.url=http://${MINIO_HOST}:${MINIO_PORT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=${MINIO_BUCKET}
minio.root-user=${MINIO_ROOT_USER}
minio.root-password=${MINIO_ROOT_PASSWORD}

# Logging
logging.level.root=INFO
logging.level.com.clara.dms=DEBUG

# Cambia el path base de la UI de Swagger
springdoc.swagger-ui.path=/swagger-ui.html