version: '3.8'
services:
  postgresql:
    container_name: postgresql_container
    image: bitnami/postgresql:15.4.0
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - POSTGRESQL_POSTGRES_PASSWORD=$DB_PASS # Password of user "postgres"
      - ALLOW_EMPTY_PASSWORD=no
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # MinIO Web Console
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server --console-address ":9001" /data
    volumes:
      - challenge_minio_data:/data
  # Include all the necessary settings to include a document management service in the stack
  # Remember to configure this service to limit the memory to 50MB
  document-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dms-service
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=$DB_HOST
      - DB_PORT=5432
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - MINIO_HOST=$MINIO_HOST
      - MINIO_PORT=$MINIO_PORT
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
      - MINIO_BUCKET=$MINIO_BUCKET
      - JAVA_OPTS=$JAVA_OPTS
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - batch_network
    depends_on:
      - postgresql
      - minio

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_minio_data:
    driver: local

networks:
  batch_network:
    driver: bridge
